-- MySQL Script generated by MySQL Workbench
-- Sex 16 Jun 2017 15:30:03 BRT
-- Model: New Model    Version: 1.5
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sifDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sifDB` ;

-- -----------------------------------------------------
-- Schema sifDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sifDB` DEFAULT CHARACTER SET utf8 ;
USE `sifDB` ;

-- -----------------------------------------------------
-- Table `sifDB`.`vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sifDB`.`vendedor` ;

CREATE TABLE IF NOT EXISTS `sifDB`.`vendedor` (
  `vendedor_id` INT NOT NULL AUTO_INCREMENT,
  `vendedor_comissao` INT NOT NULL,
  `vendedor_unidade` VARCHAR(80) NOT NULL,
  `vendedor_nome` VARCHAR(80) NOT NULL,
  `vendedor_cpf` VARCHAR(11) NOT NULL,
  `vendedor_telefone` VARCHAR(14) NOT NULL,
  `vendedor_endereco` VARCHAR(80) NOT NULL,
  `vendedor_ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `vendedor_salario` REAL NOT NULL,
  `vendedor_senha` VARCHAR(45) NOT NULL,
  `vendedor_login` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`vendedor_id`),
  UNIQUE INDEX `idvendedor_UNIQUE` (`vendedor_id` ASC),
  UNIQUE INDEX `vendedor_cpf_UNIQUE` (`vendedor_cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sifDB`.`gerente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sifDB`.`gerente` ;

CREATE TABLE IF NOT EXISTS `sifDB`.`gerente` (
  `gerente_id` INT NOT NULL AUTO_INCREMENT,
  `gerente_nome` VARCHAR(80) NOT NULL,
  `gerente_cpf` VARCHAR(11) NOT NULL,
  `gerente_endereco` VARCHAR(80) NOT NULL,
  `gerente_telefone` VARCHAR(14) NOT NULL,
  `gerente_unidade` VARCHAR(80) NOT NULL,
  `gerente_ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `gerente_salario` REAL NOT NULL,
  `gerente_senha` VARCHAR(45) NOT NULL,
  `gerente_login` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`gerente_id`),
  UNIQUE INDEX `gerente_id_UNIQUE` (`gerente_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sifDB`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sifDB`.`cliente` ;

CREATE TABLE IF NOT EXISTS `sifDB`.`cliente` (
  `cliente_id` INT NOT NULL AUTO_INCREMENT,
  `cliente_nome` VARCHAR(80) NOT NULL,
  `cliente_endereco` VARCHAR(80) NOT NULL,
  `cliente_cpf` VARCHAR(11) NOT NULL,
  `cliente_telefone` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`cliente_id`),
  UNIQUE INDEX `cliente_id_UNIQUE` (`cliente_id` ASC),
  UNIQUE INDEX `cliente_cpf_UNIQUE` (`cliente_cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sifDB`.`veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sifDB`.`veiculo` ;

CREATE TABLE IF NOT EXISTS `sifDB`.`veiculo` (
  `veiculo_id` INT NOT NULL AUTO_INCREMENT,
  `veiculo_modelo` VARCHAR(80) NOT NULL,
  `veiculo_preco` REAL NOT NULL,
  `veiculo_quantidade` INT NOT NULL,
  `veiculo_cor` VARCHAR(45) NOT NULL,
  `veiculo_ano` INT NOT NULL,
  `veiculo_ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`veiculo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sifDB`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sifDB`.`funcionario` ;

CREATE TABLE IF NOT EXISTS `sifDB`.`funcionario` (
  `funcionario_id` INT NOT NULL AUTO_INCREMENT,
  `vendedor_vendedor_id` INT NULL,
  `gerente_gerente_id` INT NULL,
  PRIMARY KEY (`funcionario_id`),
  INDEX `fk_funcionario_vendedor1_idx` (`vendedor_vendedor_id` ASC),
  INDEX `fk_funcionario_gerente1_idx` (`gerente_gerente_id` ASC),
  CONSTRAINT `fk_funcionario_vendedor1`
    FOREIGN KEY (`vendedor_vendedor_id`)
    REFERENCES `sifDB`.`vendedor` (`vendedor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_gerente1`
    FOREIGN KEY (`gerente_gerente_id`)
    REFERENCES `sifDB`.`gerente` (`gerente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sifDB`.`venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sifDB`.`venda` ;

CREATE TABLE IF NOT EXISTS `sifDB`.`venda` (
  `venda_id` INT NOT NULL AUTO_INCREMENT,
  `venda_data` DATE NOT NULL,
  `venda_precoVeiculo` REAL NOT NULL,
  `funcionario_funcionario_id` INT NOT NULL,
  `veiculo_veiculo_id` INT NOT NULL,
  `cliente_cliente_id` INT NOT NULL,
  PRIMARY KEY (`venda_id`, `funcionario_funcionario_id`, `veiculo_veiculo_id`, `cliente_cliente_id`),
  UNIQUE INDEX `venda_id_UNIQUE` (`venda_id` ASC),
  INDEX `fk_venda_funcionario1_idx` (`funcionario_funcionario_id` ASC),
  INDEX `fk_venda_veiculo1_idx` (`veiculo_veiculo_id` ASC),
  INDEX `fk_venda_cliente1_idx` (`cliente_cliente_id` ASC),
  CONSTRAINT `fk_venda_funcionario1`
    FOREIGN KEY (`funcionario_funcionario_id`)
    REFERENCES `sifDB`.`funcionario` (`funcionario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_veiculo1`
    FOREIGN KEY (`veiculo_veiculo_id`)
    REFERENCES `sifDB`.`veiculo` (`veiculo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_cliente_id`)
    REFERENCES `sifDB`.`cliente` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sifDB`.`acessorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sifDB`.`acessorio` ;

CREATE TABLE IF NOT EXISTS `sifDB`.`acessorio` (
  `acessorio_id` INT NOT NULL AUTO_INCREMENT,
  `acessorio_nome` VARCHAR(45) NOT NULL,
  `acessorio_preco` REAL NOT NULL,
  `acessorio_quantidade` INT(11) NOT NULL,
  `acessorio_descricao` VARCHAR(100) NOT NULL,
  `acessorio_ativo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`acessorio_id`),
  UNIQUE INDEX `acessorio_id_UNIQUE` (`acessorio_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sifDB`.`venda_has_acessorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sifDB`.`venda_has_acessorio` ;

CREATE TABLE IF NOT EXISTS `sifDB`.`venda_has_acessorio` (
  `venda_venda_id` INT NOT NULL,
  `venda_has_acessoriocol_preco` REAL NOT NULL,
  `acessorio_acessorio_id` INT NOT NULL,
  PRIMARY KEY (`venda_venda_id`, `acessorio_acessorio_id`),
  INDEX `fk_venda_has_acessorio_venda1_idx` (`venda_venda_id` ASC),
  INDEX `fk_venda_has_acessorio_acessorio1_idx` (`acessorio_acessorio_id` ASC),
  CONSTRAINT `fk_venda_has_acessorio_venda1`
    FOREIGN KEY (`venda_venda_id`)
    REFERENCES `sifDB`.`venda` (`venda_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_has_acessorio_acessorio1`
    FOREIGN KEY (`acessorio_acessorio_id`)
    REFERENCES `sifDB`.`acessorio` (`acessorio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
