-- MySQL Script generated by MySQL Workbench
-- Dom 04 Jun 2017 08:49:09 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- Criado: pela tua mãe, aquela puta doida que quica muito do Twitter!!!

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sifBD
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sifBD` ;

-- -----------------------------------------------------
-- Schema sifBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sifBD` DEFAULT CHARACTER SET utf8 ;
USE `sifBD` ;

-- -----------------------------------------------------
-- Table `sifBD`.`vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sifBD`.`vendedor` ;

CREATE TABLE IF NOT EXISTS `sifBD`.`vendedor` (
  `vendedor_id` INT NOT NULL AUTO_INCREMENT,
  `vendedor_comissao` INT NOT NULL,
  `vendedor_unidade` VARCHAR(80) NOT NULL,
  `vendedor_nome` VARCHAR(80) NOT NULL,
  `vendedor_cpf` VARCHAR(11) NOT NULL,
  `vendedor_telefone` VARCHAR(14) NOT NULL,
  `vendedor_endereco` VARCHAR(80) NOT NULL,
  `vendedor_ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`vendedor_id`),
  UNIQUE INDEX `idvendedor_UNIQUE` (`vendedor_id` ASC),
  UNIQUE INDEX `vendedor_cpf_UNIQUE` (`vendedor_cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sifBD`.`gerente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sifBD`.`gerente` ;

CREATE TABLE IF NOT EXISTS `sifBD`.`gerente` (
  `gerente_id` INT NOT NULL AUTO_INCREMENT,
  `gerente_nome` VARCHAR(80) NOT NULL,
  `gerente_cpf` VARCHAR(11) NOT NULL,
  `gerente_endereco` VARCHAR(80) NOT NULL,
  `gerente_telefone` VARCHAR(14) NOT NULL,
  `gerente_unidade` VARCHAR(80) NOT NULL,
  `gerente_ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`gerente_id`),
  UNIQUE INDEX `gerente_id_UNIQUE` (`gerente_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sifBD`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sifBD`.`cliente` ;

CREATE TABLE IF NOT EXISTS `sifBD`.`cliente` (
  `cliente_id` INT NOT NULL AUTO_INCREMENT,
  `cliente_nome` VARCHAR(80) NOT NULL,
  `cliente_endereco` VARCHAR(80) NOT NULL,
  `cliente_cpf` VARCHAR(11) NOT NULL,
  `cliente_telefone` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`cliente_id`),
  UNIQUE INDEX `cliente_id_UNIQUE` (`cliente_id` ASC),
  UNIQUE INDEX `cliente_cpf_UNIQUE` (`cliente_cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sifBD`.`veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sifBD`.`veiculo` ;

CREATE TABLE IF NOT EXISTS `sifBD`.`veiculo` (
  `veiculo_id` INT NOT NULL AUTO_INCREMENT,
  `veiculo_modelo` VARCHAR(80) NOT NULL,
  `veiculo_preco` REAL NOT NULL,
  `veiculo_quantidade` INT NOT NULL,
  `veiculo_cor` VARCHAR(45) NOT NULL,
  `veiculo_ano` INT NOT NULL,
  `veiculo_ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`veiculo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sifBD`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sifBD`.`funcionario` ;

CREATE TABLE IF NOT EXISTS `sifBD`.`funcionario` (
  `funcionario_id` INT NOT NULL AUTO_INCREMENT,
  `vendedor_vendedor_id` INT NOT NULL,
  `gerente_gerente_id` INT NOT NULL,
  PRIMARY KEY (`funcionario_id`, `vendedor_vendedor_id`, `gerente_gerente_id`),
  INDEX `fk_funcionario_vendedor1_idx` (`vendedor_vendedor_id` ASC),
  INDEX `fk_funcionario_gerente1_idx` (`gerente_gerente_id` ASC),
  CONSTRAINT `fk_funcionario_vendedor1`
    FOREIGN KEY (`vendedor_vendedor_id`)
    REFERENCES `sifBD`.`vendedor` (`vendedor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_gerente1`
    FOREIGN KEY (`gerente_gerente_id`)
    REFERENCES `sifBD`.`gerente` (`gerente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sifBD`.`venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sifBD`.`venda` ;

CREATE TABLE IF NOT EXISTS `sifBD`.`venda` (
  `venda_id` INT NOT NULL AUTO_INCREMENT,
  `venda_data` DATE NOT NULL,
  `venda_precoVeiculo` REAL NOT NULL,
  `funcionario_funcionario_id` INT NOT NULL,
  `veiculo_veiculo_id` INT NOT NULL,
  `cliente_cliente_id` INT NOT NULL,
  PRIMARY KEY (`venda_id`, `funcionario_funcionario_id`, `veiculo_veiculo_id`, `cliente_cliente_id`),
  UNIQUE INDEX `venda_id_UNIQUE` (`venda_id` ASC),
  INDEX `fk_venda_funcionario1_idx` (`funcionario_funcionario_id` ASC),
  INDEX `fk_venda_veiculo1_idx` (`veiculo_veiculo_id` ASC),
  INDEX `fk_venda_cliente1_idx` (`cliente_cliente_id` ASC),
  CONSTRAINT `fk_venda_funcionario1`
    FOREIGN KEY (`funcionario_funcionario_id`)
    REFERENCES `sifBD`.`funcionario` (`funcionario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_veiculo1`
    FOREIGN KEY (`veiculo_veiculo_id`)
    REFERENCES `sifBD`.`veiculo` (`veiculo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_cliente_id`)
    REFERENCES `sifBD`.`cliente` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sifBD`.`acessorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sifBD`.`acessorio` ;

CREATE TABLE IF NOT EXISTS `sifBD`.`acessorio` (
  `acessorio_id` INT NOT NULL AUTO_INCREMENT,
  `acessorio_nome` VARCHAR(45) NOT NULL,
  `acessorio_preco` REAL NOT NULL,
  `acessorio_quantidade` INT(11) NOT NULL,
  `acessorio_descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`acessorio_id`),
  UNIQUE INDEX `acessorio_id_UNIQUE` (`acessorio_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sifBD`.`venda_has_acessorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sifBD`.`venda_has_acessorio` ;

CREATE TABLE IF NOT EXISTS `sifBD`.`venda_has_acessorio` (
  `venda_venda_id` INT NOT NULL,
  `acessorio_acessorio_id` INT NOT NULL,
  `venda_has_acessoriocol_preco` REAL NOT NULL,
  `acessorio_acessorio_id1` INT NOT NULL,
  PRIMARY KEY (`venda_venda_id`, `acessorio_acessorio_id`, `acessorio_acessorio_id1`),
  INDEX `fk_venda_has_acessorio_venda1_idx` (`venda_venda_id` ASC),
  INDEX `fk_venda_has_acessorio_acessorio1_idx` (`acessorio_acessorio_id1` ASC),
  CONSTRAINT `fk_venda_has_acessorio_venda1`
    FOREIGN KEY (`venda_venda_id`)
    REFERENCES `sifBD`.`venda` (`venda_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_has_acessorio_acessorio1`
    FOREIGN KEY (`acessorio_acessorio_id1`)
    REFERENCES `sifBD`.`acessorio` (`acessorio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

